# Compose for setting up local dev environment. For developing UI. This includes:
#    - Configurator
#    - Postgres and Clickhouse (optional; todo) to test destinations configurations
# Configurator is started at localhost:9875
# Run UI with BACKEND_API_BASE=http://localhost:9875 to use local backend

version: "2.3"
networks:
  main:

services:
  configurator:
    container_name: jitsu_configurator
    build:
      context: .
      dockerfile: configurator.Dockerfile
      args:
        SKIP_UI: 'true'
    entrypoint: './configurator'
    environment:
      - SERVER_AUTH=8b64e097c08a43c7ab656b7b02997859
      - SERVER_NAME=devconf
      - STORAGE_REDIS_HOST=redis
      - STORAGE_REDIS_PORT=6379
      - AUTH_REDIS_HOST=redis
      - AUTH_REDIS_PORT=6379
      - AUTH_REDIS_REFRESH_SECRET=0bf8478623224f6ea8354703b2e8c31f
      - AUTH_REDIS_REFRESH_SECRET=3bd3e114f4ba4872b1d8b067de634097
      - CONFIGURATOR_ADMIN_TOKEN=8b64e097c08a43c7ab656b7b02997859
    depends_on:
      - redis
    volumes:
      - ./ui-dev-compose/configurator/data:/home/configurator/data/
    restart: always
    ports:
      - "7000:9875"
    networks:
      - main
  redis:
    container_name: jitsu_redis
    image: redis:5.0-alpine
    volumes:
      - ./ui-dev-compose/configurator/redis/data:/data
    restart: always
    networks:
      - main