version: "2.3"
networks:
  main:

services:
  configurator:
    container_name: jitsu_configurator
    build:
      context: .
      dockerfile: configurator.Dockerfile
      args:
        SKIP_UI_BUILD: 'false'
    environment:
      - SERVER_ADMIN_TOKEN=${SERVER_ADMIN_TOKEN}
      - CONFIGURATOR_ADMIN_TOKEN=${CONFIGURATOR_ADMIN_TOKEN}
    image: jitsucom/configurator:latest
    depends_on:
      - redis
    volumes:
      - ./compose-data/configurator/data:/home/configurator/data/
    restart: always
    ports:
      - "7000:7000"
    networks:
      - main
  server:
    container_name: jitsu_server
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - SERVER_ADMIN_TOKEN=${SERVER_ADMIN_TOKEN}
      - CONFIGURATOR_ADMIN_TOKEN=${CONFIGURATOR_ADMIN_TOKEN}
    image: jitsucom/server:latest
    depends_on:
      - configurator
      - redis
    restart: always
    volumes:
      - ./compose-data/server/data:/home/eventnative/data/
    ports:
      - "8001:8001"
    networks:
      - main
  redis:
    container_name: jitsu_redis
    image: redis:5.0-alpine
    volumes:
      - ./compose-data/redis/data:/data
    restart: always
    networks:
      - main