version: "2.3"
networks:
  main:

services:
  configurator:
    container_name: jitsu_configurator
    build:
      context: .
      dockerfile: configurator.Dockerfile
    image: jitsucom/configurator:latest
    depends_on:
      - redis
    volumes:
      - ./compose-data/configurator/res:/home/configurator/app/res/
      - ./compose-data/configurator/logs/:/home/configurator/logs/
    restart: always
    ports:
      - "7000:7000"
    networks:
      - main
  server:
    container_name: jitsu_server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: jitsucom/server:latest
    depends_on:
      - configurator
      - redis
    restart: always
    volumes:
      - ./compose-data/server/res:/home/eventnative/app/res/
      - ./compose-data/server/logs/:/home/eventnative/logs/
      - ./compose-data/server/events:/home/eventnative/logs/events/
    ports:
      - "8001:8001"
    networks:
      - main
  redis:
    container_name: jitsu_redis
    image: redis:5.0-alpine
    volumes:
      - ./compose-data/redis/data:/data
    restart: always
    networks:
      - main