server:
  log:
    level: info
  domain: herokuapp.com
  name: demo-jitsu
  auth: '${env.CONFIGURATOR_ADMIN_TOKEN}'

storage:
  redis:
    host: '${env.REDIS_TLS_URL}'

jitsu:
  base_url: 'http://localhost:8001'
  admin_token: '${env.SERVER_ADMIN_TOKEN}'

auth:
  redis:
    host: '${env.REDIS_TLS_URL}'
    access_secret: access
    refresh_secret: refresh