server:
  log:
    level: debug
  domain: localhost
  name: demo-eventnative
  auth: 'a123'

storage:
  redis:
    host: redis
    port: 6379

eventnative:
  base_url: "http://server:8001/api/v1"
  admin_token: 'a123'


destinations:
  statistics:
    redis:
      host: redis
      port: 6379

auth:
  redis:
    host: redis
    port: 6379
    access_secret: access
    refresh_secret: refresh

smtp:
  host: 'smtp.sendgrid.net'
  port: 587
  user: apikey
  password: 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