build_ksense: &build_ksense
  run:
    name: Build and Push DEPRECATED ksense EventNative Docker image
    command: |
      DOCKER_BUILDKIT=1 docker build --build-arg dhid=ksense -t $IMAGE_NAME:$IMAGE_VERSION -f $DOCKER_FILE .
      echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      docker push $IMAGE_NAME

setup_image_version: &setup_image_version
  run:
    name: Set up IMAGE_VERSION env var
    command: |
      echo 'export IMAGE_VERSION=${CIRCLE_TAG//v}' >> $BASH_ENV

version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/jitsucom/jitsu
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-global-{{ checksum "./go.sum" }}
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
      # uncomment it for stopping build on golint error
      # - run: golint -set_exit_status=true ./...
      - save_cache:
          key: go-mod-v1-global-{{ checksum "./go.sum" }}
          paths:
            - "/go/pkg/mod"
  server-test:
    working_directory: /go/src/github.com/jitsucom/jitsu/server
    docker:
      - image: circleci/golang:1.14
      - image: yandex/clickhouse-server:20.3
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
      - image: circleci/redis
    environment:
      PG_TEST_PORT: 5432
      CH_TEST_PORT: 8123
      REDIS_TEST_PORT: 6379
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "./server/go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Waiting for Redis to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 6379 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Redis && exit 1
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            cd server && make test_backend | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
      - run: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "./server/go.sum" }}
          paths:
            - "/go/pkg/mod"

  build-latest-en-docker:
    environment:
      IMAGE_NAME: ksense/eventnative
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: latest
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - <<: *build_ksense

  build-beta-en-docker:
    environment:
      IMAGE_NAME: ksense/eventnative
      DOCKER_FILE: server.Dockerfile
      IMAGE_VERSION: beta
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - <<: *build_ksense

  build-tagged-en-docker:
    environment:
      IMAGE_NAME: ksense/eventnative
      DOCKER_FILE: server.Dockerfile
    docker:
      - image: cimg/go:1.14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - <<: *setup_image_version
      - <<: *build_ksense

workflows:
  version: 2.1
  build-docker:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - server-test:
          context: jitsu
          requires:
            - lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build-latest-en-docker:
          context: eventnative
          requires:
            - server-test
          filters:
            branches:
              only: master
      - build-beta-en-docker:
          context: eventnative
          requires:
            - server-test
          filters:
            branches:
              only: beta
      - build-tagged-en-docker:
          context: eventnative
          requires:
            - server-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/