name: Continuous Integration

on:
  pull_request:
  push:
    branches: [master, beta]

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    env:
      working-directory: ./configurator/frontend


    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - run: yarn check:all
