name: Go

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master, beta ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Server
      run: |
        go mod tidy
        go build -v ./...
      working-directory: ./server

    - name: Test Server
      run: go test -v ./...
      working-directory: ./server
      
    - name: Build Backend
      run: |
        go mod tidy
        go build -v ./...
      working-directory: ./configurator/backend

