name: Go

on:
  push:
    branches: 
      - '**'
#  pull_request:
#    branches: [ master, beta ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
        #  ~/.cache/go-build
        #  ~/Library/Caches/go-build
        #  %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build Backend
      run: |
        go mod tidy
        go build
      working-directory: ./configurator/backend
          
    - name: Build Server
      run: |
        go mod tidy
        go build
      working-directory: ./server

    - name: Test Server
      run: |
        go install github.com/vakenbolt/go-test-report@latest
        go test -failfast -v -parallel=1 -json ./... | ~/go/bin/go-test-report
      working-directory: ./server

    - uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: |
          ./server/test_report.html

