name: Go

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master, beta ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: pwd
      run: pwd
      
    - name: ls
      run: ls -al

    - name: Build
      run: go build -v ./jitsu/server/...

    - name: Test
      run: go test -v ./jitsu/server/...
