name: Deploy jitsu.com to vercel

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: CultureHQ/actions-yarn@v1.0.1
      - name: Run vercel deploy
        run: yarn vercel --prod

